# Generated by Django 2.2.4 on 2019-08-10 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_programming_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programming',
            name='language',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='programming',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
